// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: weft.proto

package weftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Weft_Search_FullMethodName = "/weft.v1.Weft/Search"
)

// WeftClient is the client API for Weft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Weft is weft's own search surface, in a second encoding.
//
// It is the same request and the same engine as POST /{index}/_weft/search —
// see docs/API.md. Nothing here decides anything: the service converts protobuf
// to opensearch.NativeRequest, calls opensearch.NativeSearch, and converts what
// comes back. A test in this module fails the build if a field exists on one
// side and not the other, because two surfaces that drift are two answers to
// one question.
type WeftClient interface {
	// Search fuses the named streams and returns one page of the ranking.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type weftClient struct {
	cc grpc.ClientConnInterface
}

func NewWeftClient(cc grpc.ClientConnInterface) WeftClient {
	return &weftClient{cc}
}

func (c *weftClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Weft_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeftServer is the server API for Weft service.
// All implementations must embed UnimplementedWeftServer
// for forward compatibility.
//
// Weft is weft's own search surface, in a second encoding.
//
// It is the same request and the same engine as POST /{index}/_weft/search —
// see docs/API.md. Nothing here decides anything: the service converts protobuf
// to opensearch.NativeRequest, calls opensearch.NativeSearch, and converts what
// comes back. A test in this module fails the build if a field exists on one
// side and not the other, because two surfaces that drift are two answers to
// one question.
type WeftServer interface {
	// Search fuses the named streams and returns one page of the ranking.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedWeftServer()
}

// UnimplementedWeftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeftServer struct{}

func (UnimplementedWeftServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWeftServer) mustEmbedUnimplementedWeftServer() {}
func (UnimplementedWeftServer) testEmbeddedByValue()              {}

// UnsafeWeftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeftServer will
// result in compilation errors.
type UnsafeWeftServer interface {
	mustEmbedUnimplementedWeftServer()
}

func RegisterWeftServer(s grpc.ServiceRegistrar, srv WeftServer) {
	// If the following call panics, it indicates UnimplementedWeftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Weft_ServiceDesc, srv)
}

func _Weft_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeftServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Weft_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeftServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Weft_ServiceDesc is the grpc.ServiceDesc for Weft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weft.v1.Weft",
	HandlerType: (*WeftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Weft_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weft.proto",
}
