// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: weft.proto

package weftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index to search. There is no cluster and no alias; this is a directory
	// name under the server's data root.
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// One leaf clause per entry, as JSON, in the spelling `_search` already
	// accepts: `{"match":{"text":"rank fusion"}}`, `{"knn":{"vec":{...}}}`,
	// `{"weft_graph":{"seeds":["doc-3"]}}`.
	//
	// JSON and not a oneof over the clause kinds, which is a deliberate refusal
	// rather than a shortcut. A oneof would be a second list of what a stream can
	// be, kept in step by hand with `compiler.clause` — and D-034 rejected exactly
	// that list on the HTTP side, on the grounds that it drifts on the first
	// clause added to one surface and not the other. The query language here is
	// JSON-shaped; typing it in proto would make this file its second definition.
	//
	// The *response* is fully typed, which is where a client actually wants types.
	Streams []string `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	// One weight per entry of streams, or empty for an unweighted fusion.
	//
	// Positional, which is what lets a weight exist without fusion learning what a
	// stream holds. A list of a different length is refused rather than padded: an
	// unequal list would weight a stream the client did not mean.
	//
	// A weight of 0 is not the short spelling of "do not vote" — it removes the
	// document from the fused result entirely.
	Weights []float64 `protobuf:"fixed64,3,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	// The page. Zero means the server default of 10.
	Size int32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	From int32 `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	// How many candidates the fusion produces before the page is cut. Zero means
	// from+size. This is separate from size on purpose: rank fusion reads
	// position, so a deeper fusion changes the ranking and not only its length.
	Depth int32 `protobuf:"varint,6,opt,name=depth,proto3" json:"depth,omitempty"`
	// Ask for the pre-fusion rank of every stream, per hit.
	Breakdown     bool `protobuf:"varint,7,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_weft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_weft_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *SearchRequest) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *SearchRequest) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *SearchRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SearchRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *SearchRequest) GetBreakdown() bool {
	if x != nil {
		return x.Breakdown
	}
	return false
}

type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hits  []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// How many candidates the fusion produced before the page was cut. It is a
	// lower bound unless exact is set — the search returns a top-k, so a full
	// prefix says only that at least this many matched.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Exact         bool  `protobuf:"varint,3,opt,name=exact,proto3" json:"exact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_weft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_weft_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

type Hit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// The document body as it was indexed, verbatim JSON.
	Source []byte `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// One entry per stream the request named, in that order, holding where that
	// stream ranked this document before fusion saw any of them. Empty unless the
	// request asked for it.
	Breakdown     []*Rank `protobuf:"bytes,4,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_weft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_weft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_weft_proto_rawDescGZIP(), []int{2}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Hit) GetBreakdown() []*Rank {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

// Rank is a stream's own placement, or the absence of one.
//
// A message rather than a bare int32 because "this stream had no opinion" is a
// third thing, and proto3 has no null: an absent document encoded as 0 would
// look like one every stream ranked first. present=false is the `-` column in
// examples/breakdown.
type Rank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	At            int32                  `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_weft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_weft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_weft_proto_rawDescGZIP(), []int{3}
}

func (x *Rank) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *Rank) GetAt() int32 {
	if x != nil {
		return x.At
	}
	return 0
}

var File_weft_proto protoreflect.FileDescriptor

const file_weft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"weft.proto\x12\aweft.v1\"\xb5\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x18\n" +
	"\astreams\x18\x02 \x03(\tR\astreams\x12\x18\n" +
	"\aweights\x18\x03 \x03(\x01R\aweights\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x12\n" +
	"\x04from\x18\x05 \x01(\x05R\x04from\x12\x14\n" +
	"\x05depth\x18\x06 \x01(\x05R\x05depth\x12\x1c\n" +
	"\tbreakdown\x18\a \x01(\bR\tbreakdown\"^\n" +
	"\x0eSearchResponse\x12 \n" +
	"\x04hits\x18\x01 \x03(\v2\f.weft.v1.HitR\x04hits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05exact\x18\x03 \x01(\bR\x05exact\"p\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x03 \x01(\fR\x06source\x12+\n" +
	"\tbreakdown\x18\x04 \x03(\v2\r.weft.v1.RankR\tbreakdown\"0\n" +
	"\x04Rank\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x05R\x02at2A\n" +
	"\x04Weft\x129\n" +
	"\x06Search\x12\x16.weft.v1.SearchRequest\x1a\x17.weft.v1.SearchResponseB.Z,github.com/skyoo2003/weft/grpc/weftpb;weftpbb\x06proto3"

var (
	file_weft_proto_rawDescOnce sync.Once
	file_weft_proto_rawDescData []byte
)

func file_weft_proto_rawDescGZIP() []byte {
	file_weft_proto_rawDescOnce.Do(func() {
		file_weft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weft_proto_rawDesc), len(file_weft_proto_rawDesc)))
	})
	return file_weft_proto_rawDescData
}

var file_weft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weft_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: weft.v1.SearchRequest
	(*SearchResponse)(nil), // 1: weft.v1.SearchResponse
	(*Hit)(nil),            // 2: weft.v1.Hit
	(*Rank)(nil),           // 3: weft.v1.Rank
}
var file_weft_proto_depIdxs = []int32{
	2, // 0: weft.v1.SearchResponse.hits:type_name -> weft.v1.Hit
	3, // 1: weft.v1.Hit.breakdown:type_name -> weft.v1.Rank
	0, // 2: weft.v1.Weft.Search:input_type -> weft.v1.SearchRequest
	1, // 3: weft.v1.Weft.Search:output_type -> weft.v1.SearchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weft_proto_init() }
func file_weft_proto_init() {
	if File_weft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weft_proto_rawDesc), len(file_weft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weft_proto_goTypes,
		DependencyIndexes: file_weft_proto_depIdxs,
		MessageInfos:      file_weft_proto_msgTypes,
	}.Build()
	File_weft_proto = out.File
	file_weft_proto_goTypes = nil
	file_weft_proto_depIdxs = nil
}
